apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leyline-open-api.fullname" . }}
  labels:
    {{- include "leyline-open-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "leyline-open-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "leyline-open-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "leyline-open-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "leyline-open-api.fullname" . }}-db-secret
                  key: DATABASE_URL
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      restartPolicy: Always
