apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leyline.fullname" . }}-db-secret
  labels:
    {{- include "leyline.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
