apiVersion: v1
kind: Service
metadata:
  name: {{ include "leyline.fullname" . }}
  labels:
    {{- include "leyline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "leyline.name" . }}
    release: {{ .Release.Name }}
