name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./leyline-open-api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      working-directory: leyline-open-api
      run: |
        pylint app --disable=C0114,C0115,C0116
          
    - name: Run tests
      working-directory: leyline-open-api
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings  

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: leyline-open-api/reports/

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      working-directory: ./leyline-open-api
      run: |
        docker build -t leyline-open-api:latest .

    - name: Build Helm chart
      run: |
        helm lint ./helm

